-- tic-tac-toe.cabal
name:                tic-tac-toe
version:             0.1.0.0
description:         A game of tic-tac-toe
category:            CLI
build-type:          Simple
cabal-version:       >= 2.0

executable cli
  main-is:             Main.hs
  hs-source-dirs:      src
  default-language:    Haskell2010
  build-depends:       base >=4.7 && <5
                     , ansi-terminal

executable web
  main-is:             Main.hs
  hs-source-dirs:      app
  default-language:    Haskell2010
  build-depends:    base ^>=4.18.2.1, scotty, mustache, parsec, text, mtl, unliftio-core, stm, array, random
